"""
Flask Web Application for Image Captioning and Text-to-Speech

This application provides a cyberpunk-themed web interface for:
1. Uploading images
2. Generating AI-powered captions using Hugging Face's BLIP model
3. Transforming captions into different creative modes (caption, story, poetic, funny)
4. Converting captions to speech with various emotional styles
5. Displaying results with an immersive cyberpunk UI

The application is optimized for M1 Mac systems with Metal Performance Shaders (MPS) support
for GPU acceleration of the image captioning model.
"""

from flask import Flask, render_template, request, redirect, url_for, flash
from werkzeug.utils import secure_filename
import os
import logging
import random
from caption_model import get_caption_model, generate_caption
from audio_generator import text_to_audio

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
# Configure logging to track application events, errors, and debugging information
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ============================================================================
# FLASK APPLICATION SETUP
# ============================================================================
# Initialize the Flask application instance
app = Flask(__name__)

# Secret key for session management and flash messages
# In production, this should be stored as an environment variable
app.secret_key = 'cyberpunk-secret-key-2024'

# Configure upload folder for storing uploaded images
app.config['UPLOAD_FOLDER'] = 'static/uploads'

# Configure audio folder for storing generated audio files
app.config['AUDIO_FOLDER'] = 'static/audio'

# Set maximum file upload size to 16MB to prevent memory issues
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024  # 16MB max file size

# ============================================================================
# FILE VALIDATION
# ============================================================================
# Set of allowed image file extensions for security
# Only these formats will be accepted for upload
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif', 'webp'}


def apply_mode_to_caption(caption: str, mode: str) -> str:
    """
    Transform a base image caption into different creative formats based on the selected mode.
    
    This function takes the plain caption generated by the BLIP model and applies creative
    transformations to create different narrative styles. Each mode has multiple variations
    that are randomly selected to provide variety.
    
    Args:
        caption (str): The base caption generated by the BLIP model (plain text description)
        mode (str): The transformation mode to apply. Valid options:
            - 'caption': Enhanced captions with cyberpunk-themed additions
            - 'story': Full narrative stories with opening, middle, twist, and ending
            - 'poetic': Multi-line poetry with cyberpunk imagery
            - 'funny': Humorous captions with tech-related punchlines
    
    Returns:
        str: The transformed caption text based on the selected mode.
             Returns the original caption if mode is invalid or caption is empty.
    
    Note:
        The function uses random selection for variations within each mode to ensure
        different outputs even with the same base caption.
    """
    # Early return if caption is empty or None
    if not caption:
        return caption

    # Clean up the base caption: remove trailing periods and whitespace
    base = caption.strip().rstrip(".")
    
    # Create a lowercase version for natural sentence integration
    # This is used in story mode to make the caption flow naturally in sentences
    scene = base[0].lower() + base[1:] if len(base) > 1 else base

    # ========================================================================
    # MODE: CAPTION - Enhanced captions with cyberpunk atmosphere
    # ========================================================================
    if mode == "caption":
        # Multiple variations of enhanced captions with cyberpunk-themed additions
        variants = [
            base,  # Original caption
            f"{base}. A moment frozen in neon light.",
            f"{base}, framed by the distant hum of the city.",
            f"{base}. It looks like a still from a sci-fi movie.",
            f"{base}. You can almost hear the electricity in the air.",
        ]
        return random.choice(variants)

    # ========================================================================
    # MODE: STORY - Full narrative with cyberpunk storytelling elements
    # ========================================================================
    if mode == "story":
        # Opening sentences that set a cyberpunk scene
        openings = [
            f"In a forgotten corner of the city, {scene}.",
            f"On a night when the neon refused to sleep, {scene}.",
            f"Somewhere between dream and glitch, {scene}.",
        ]
        
        # Middle sections that build atmosphere with cyberpunk imagery
        middles = [
            " Rain slid down chrome and glass, turning every light into a streak of color.",
            " The streets hummed with drones, tired footsteps, and quiet conversations no one was meant to hear.",
            " Above, billboards argued in looping holograms while the sky pretended not to notice.",
        ]
        
        # Plot twists that add intrigue to the narrative
        twists = [
            " Someone passing by felt the strange certainty that this moment mattered.",
            " A stranger stopped, saving the scene in their memory like a secret file.",
            " No one realized this tiny scene would start a chain of events that couldn't be undone.",
        ]
        
        # Ending sentences that provide closure with cyberpunk themes
        endings = [
            " By morning, the city would be exactly the same—except for one person who finally decided to change.",
            " When the sun finally pushed through the clouds, the world looked identical, but the story had already shifted.",
            " Long after the lights dimmed, the echo of that moment kept rewriting itself in the network's memory.",
        ]

        # Combine random selections from each section to create a unique story
        story = random.choice(openings) + random.choice(middles) + \
                random.choice(twists) + " " + random.choice(endings)
        return story

    # ========================================================================
    # MODE: POETIC - Multi-line poetry with cyberpunk imagery
    # ========================================================================
    if mode == "poetic":
        # Different poetic templates, each with the caption as the first line
        templates = [
            f"{base}.\n"
            "Neon drips down the glass,\n"
            "Shadows lean into the rain,\n"
            "Circuits whisper under tired boots,\n"
            "And the city pretends not to dream.",

            f"{base}.\n"
            "Pixels blur into midnight,\n"
            "Billboards breathe electric prayers,\n"
            "Somewhere, a quiet signal blinks,\n"
            "waiting for someone to notice.",

            f"{base}.\n"
            "Chrome and moonlight share a secret,\n"
            "Cables curl like restless thoughts,\n"
            "A heartbeat hides in every screen,\n"
            "and the future watches from the corner.",
        ]
        return random.choice(templates)

    # ========================================================================
    # MODE: FUNNY - Humorous captions with tech-related humor
    # ========================================================================
    if mode == "funny":
        # Setup phrases that introduce the caption in a humorous context
        setups = [
            f"{base.capitalize()}, which is exactly what happens",
            f"{base.capitalize()} — honestly, this is what you get",
            f"{base.capitalize()}. This is the natural result",
        ]
        
        # Punchline phrases that add tech humor
        punches = [
            " when you let an AI design the future after three energy drinks.",
            " when nobody reads the terms and conditions but clicks accept anyway.",
            " when the Wi-Fi is strong but the life choices are weak.",
            " when someone says, 'How bad could it be?' and the universe takes it personally.",
        ]
        
        # Ending phrases that add a final humorous touch
        endings = [
            " Somewhere, a server is facepalming in 4K.",
            " An AI just added this to its 'are you sure?' folder.",
            " The cloud is laughing, but your storage is full.",
        ]
        return random.choice(setups) + random.choice(punches) + " " + random.choice(endings)

    # Default: return the original caption if mode is not recognized
    return caption


# ============================================================================
# MODEL INITIALIZATION
# ============================================================================
# Load the image captioning model at application startup
# This ensures the model is ready when the first request comes in
# The model is loaded once and reused for all subsequent requests (singleton pattern)
logger.info("Initializing image captioning model...")
try:
    get_caption_model()  # This loads the model at startup
    logger.info("Image captioning model loaded successfully")
except Exception as e:
    logger.error(f"Error loading captioning model: {str(e)}")
    logger.warning("App will continue but caption generation may fail")


def allowed_file(filename: str) -> bool:
    """
    Validate that the uploaded file has an allowed extension.
    
    This security check prevents users from uploading potentially dangerous file types.
    Only image files with recognized extensions are allowed.
    
    Args:
        filename (str): The name of the uploaded file
    
    Returns:
        bool: True if the file extension is in the ALLOWED_EXTENSIONS set, False otherwise
    
    Example:
        >>> allowed_file("image.jpg")
        True
        >>> allowed_file("script.exe")
        False
    """
    # Check if filename contains a dot (indicating an extension)
    # and if the extension (lowercased) is in the allowed set
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


# ============================================================================
# ROUTE HANDLERS
# ============================================================================
@app.route('/', methods=['GET', 'POST'])
def index():
    """
    Main route handler for the application.
    
    Handles both GET and POST requests:
    - GET: Displays the upload form (empty state or with previous results)
    - POST: Processes image upload, generates caption, creates audio, and displays results
    
    Workflow for POST requests:
    1. Validate file upload and extract mode/emotion preferences
    2. Save uploaded image to disk
    3. Generate base caption using BLIP model
    4. Transform caption based on selected mode
    5. Generate audio file with selected emotion
    6. Render template with all results
    
    Returns:
        Rendered HTML template with:
            - uploaded_image: Path to the uploaded image (if uploaded)
            - caption: Generated/transformed caption text
            - audio_path: Path to generated audio file
            - mode: Selected caption mode
            - emotion: Selected audio emotion
    """
    # Initialize variables for template rendering
    uploaded_image = None  # Path to uploaded image file
    caption = None        # Generated/transformed caption text
    audio_path = None     # Path to generated audio file
    mode = 'caption'      # Default caption mode
    emotion = 'calm'      # Default audio emotion
    
    # ========================================================================
    # POST REQUEST HANDLING - Process file upload
    # ========================================================================
    if request.method == 'POST':
        # Extract user preferences from form data
        # These determine how the caption is transformed and how audio is generated
        mode = request.form.get('mode', 'caption')      # Caption transformation mode
        emotion = request.form.get('emotion', 'calm')   # Audio emotion style
        
        # Validate that a file was included in the request
        if 'file' not in request.files:
            flash('No file selected')
            return redirect(request.url)
        
        file = request.files['file']
        
        # Check if user actually selected a file (not just empty form submission)
        if file.filename == '':
            flash('No file selected')
            return redirect(request.url)
        
        # ====================================================================
        # FILE VALIDATION AND SAVING
        # ====================================================================
        if file and allowed_file(file.filename):
            # Sanitize filename to prevent directory traversal attacks
            # secure_filename removes dangerous characters and path components
            filename = secure_filename(file.filename)
            
            # Ensure upload directories exist (create if they don't)
            os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)
            os.makedirs(app.config['AUDIO_FOLDER'], exist_ok=True)
            
            # Construct full file path and save the uploaded file
            filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
            file.save(filepath)
            uploaded_image = filepath  # Store path for template rendering
            
            # ================================================================
            # CAPTION GENERATION
            # ================================================================
            try:
                logger.info(f"Generating caption for image: {filepath}")
                
                # Generate base caption using BLIP model
                # This is the plain description of the image
                base_caption = generate_caption(filepath)
                logger.info(f"Base caption: {base_caption}")

                # Transform the caption based on selected mode
                # This applies creative transformations (story, poetic, funny, etc.)
                caption = apply_mode_to_caption(base_caption, mode)
                logger.info(f"Final text for mode '{mode}': {caption}")

                # ============================================================
                # AUDIO GENERATION
                # ============================================================
                # Generate audio only if caption was successfully created
                if caption and caption != "Unable to generate caption":
                    try:
                        logger.info("Generating audio from caption...")
                        
                        # Convert text to speech with selected emotion
                        # The emotion parameter affects audio processing (speed, volume, effects)
                        audio_path = text_to_audio(
                            caption,                    # Text to convert to speech
                            app.config['AUDIO_FOLDER'], # Directory to save audio file
                            filename,                    # Base filename for audio file
                            emotion                      # Emotion style for audio processing
                        )
                        
                        if audio_path:
                            logger.info(f"Audio generated successfully: {audio_path}")
                        else:
                            logger.warning("Failed to generate audio")
                    except Exception as e:
                        # Log error but continue - image and caption will still be displayed
                        logger.error(f"Error generating audio: {str(e)}")
                        flash(f'Error generating audio: {str(e)}')
            except Exception as e:
                # Log caption generation error
                logger.error(f"Error generating caption: {str(e)}")
                flash(f'Error generating caption: {str(e)}')
                # Set fallback caption so image can still be displayed
                caption = "Unable to generate caption"
        else:
            # Invalid file type - show error and redirect
            flash('Invalid file type. Please upload an image (png, jpg, jpeg, gif, webp)')
            return redirect(request.url)
    
    # ========================================================================
    # RENDER TEMPLATE
    # ========================================================================
    # Render the HTML template with all the data
    # Template will display upload form, image, caption, and audio player
    return render_template(
        'index.html',
        uploaded_image=uploaded_image,
        caption=caption,
        audio_path=audio_path,
        mode=mode,
        emotion=emotion
    )


# ============================================================================
# APPLICATION ENTRY POINT
# ============================================================================
if __name__ == '__main__':
    # Ensure required directories exist before starting the server
    os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)
    os.makedirs(app.config['AUDIO_FOLDER'], exist_ok=True)
    
    # Start the Flask development server
    # debug=True enables auto-reload on code changes and detailed error pages
    # host='0.0.0.0' makes the server accessible from other devices on the network
    # port=8000 sets the port number (default is 5000)
    app.run(debug=True, host='0.0.0.0', port=8000)
